# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  sandra-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: sandra-mysql
    volumes:
      - sandra-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sandra
      - MYSQL_DATABASE=sandra
      - MYSQL_USER=sandra
      - MYSQL_PASSWORD=sandra

  # PHP 7.3 + nginx
  app:
    image: ambientum/php:latest-nginx
    container_name: sandra-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql